# octopus config file

octopus:
  environments:
    - development
    - production
  development:
    slave:
      adapter: mysql2
      database: amigo_tt_2017_dec # amigo_tt_2018_mar
      host: dev.os.gionee.com # 18.8.5.10

      username: root
      password: root
      encoding: utf8
  production:
    slave:
      adapter: mysql2
      database: amigo_tt_2017_dec
      host: dev.os.gionee.com

      username: root
      password: root
      encoding: utf8
