
s = {:tasks => [{:personal_task=>{:name=>"我的个人任务", :url=>"/my/tasks?type=personal_task&person_type=assigned_to_id", :count=>2}},
           {:issue_to_special_test_result=>{:name=>"我的专项测试任务", :url=>"/my/tasks?type=issue_to_special_test_task", :count=>1}},
           {:issue_to_merge=>{:name=>"我的合入问题任务", :url=>"/my/tasks?type=issue_to_merge_task", :count=>245}}
          ],
 :issues => [{21 => {:name => '提交', :url => "#", :count => 0}},
             {24 => {:name => '无法理解', :url => "#", :count => 0}},
             {7 =>  {:name => '分配', :url => "#", :count => 0}},
             {8 =>  {:name => '重分配', :url => "#", :count => 0}},
             {9  =>  {:name => '打开', :url => "#", :count => 0}},
             {14 => {:name => '拒绝', :url => "#", :count => 0}},
             {15 => {:name => '重复', :url => "#", :count => 0}},
             {23 => {:name => '申请裁决', :url => "#", :count => 0}},
             {20 => {:name => '裁决', :url => "#", :count => 0}},
             {10 => {:name => '重打开', :url => "#", :count => 0}},
             {22 => {:name => '三方分析', :url => "#", :count => 0}},
           ],
 :issue_total => 0,
 :task_total=>248,
 :total_count=>248}